import {
  deleteLocalModel,
  downloadLocalModel,
  getCudaRuntimeStatus,
  getSenseVoiceStatus,
  listLocalModels,
  downloadCudaRuntime,
  deleteCudaRuntime,
  downloadSenseVoice,
  cancelSenseVoiceDownload,
  deleteSenseVoice,
  setSenseVoiceModel,
  setLocalComputeMode,
  onLocalModelDownloadProgress,
  onSenseVoiceDownloadProgress,
  onCudaRuntimeDownloadProgress,
  saveTranscriptionProfile,
  deleteProfile,
  setActiveProfile,
  setFallbackTranscriptionProfile,
  testProfile,
  hasProfileCredential,
} from '../../lib/bridge';
import { attachLateSafeListener } from './events';

export const transcriptionPlatform = {
  listLocalModels,
  downloadLocalModel,
  deleteLocalModel,
  getCudaRuntimeStatus,
  downloadCudaRuntime,
  deleteCudaRuntime,
  setLocalComputeMode,
  getSenseVoiceStatus,
  downloadSenseVoice,
  cancelSenseVoiceDownload,
  deleteSenseVoice,
  setSenseVoiceModel,
  saveTranscriptionProfile,
  deleteProfile,
  setActiveProfile,
  setFallbackTranscriptionProfile,
  testProfile,
  hasProfileCredential,
  onLocalModelDownloadProgress,
  onSenseVoiceDownloadProgress,
  onCudaRuntimeDownloadProgress,
  attachLateSafeListener,
} as const;
